/*
	## Nikko Renolds
	## https://github.com/Ni1kko/FrameworkV2
    ## RscTitleNameTags.hpp
*/

class RscTitleNameTags 
{
    idd = 11202;
    duration = INFINTE;
    onLoad = "uiNamespace setVariable ['RscTitleNameTags',_this select 0]";
    onUnload="uiNamespace setVariable ['RscTitleNameTags', displayNull]";
    onDestroy="uiNamespace setVariable ['RscTitleNameTags', displayNull]";
    objects[] = {};

    class controls
    {
        class BaseIcon
        {
            idc = -1;
            type = 13;
            style = 0;
            colorText[] = {1,1,1,1};
            colorBackground[] = {0,0,0,0};
            font = "PuristaMedium";
            text = "";
            size = 0.04;
            shadow = 1.5;
            w = 0; h = 0;
            x = 0.1; y = 0.1;
        };

        class p1 : BaseIcon {idc = NAMETAG_IDC_BASE;};
        class p2 : BaseIcon {idc = NAMETAG_IDC_BASE + 1;};
        class p3 : BaseIcon {idc = NAMETAG_IDC_BASE + 2;};
        class p4 : BaseIcon {idc = NAMETAG_IDC_BASE + 3;};
        class p5 : BaseIcon {idc = NAMETAG_IDC_BASE + 4;};
        class p6 : BaseIcon {idc = NAMETAG_IDC_BASE + 5;};
        class p7 : BaseIcon {idc = NAMETAG_IDC_BASE + 6;};
        class p8 : BaseIcon {idc = NAMETAG_IDC_BASE + 7;};
        class p9 : BaseIcon {idc = NAMETAG_IDC_BASE + 8;};
        class p10 : BaseIcon {idc = NAMETAG_IDC_BASE + 9;};
        class p11 : BaseIcon {idc = NAMETAG_IDC_BASE + 10;};
        class p12 : BaseIcon {idc = NAMETAG_IDC_BASE + 11;};
        class p13 : BaseIcon {idc = NAMETAG_IDC_BASE + 12;};
        class p14 : BaseIcon {idc = NAMETAG_IDC_BASE + 13;};
        class p15 : BaseIcon {idc = NAMETAG_IDC_BASE + 14;};
        class p16 : BaseIcon {idc = NAMETAG_IDC_BASE + 15;};
        class p17 : BaseIcon {idc = NAMETAG_IDC_BASE + 16;};
        class p18 : BaseIcon {idc = NAMETAG_IDC_BASE + 17;};
        class p19 : BaseIcon {idc = NAMETAG_IDC_BASE + 18;};
        class p20 : BaseIcon {idc = NAMETAG_IDC_BASE + 19;};
        class p21 : BaseIcon {idc = NAMETAG_IDC_BASE + 20;};
        class p22 : BaseIcon {idc = NAMETAG_IDC_BASE + 21;};
        class p23 : BaseIcon {idc = NAMETAG_IDC_BASE + 22;};
        class p24 : BaseIcon {idc = NAMETAG_IDC_BASE + 23;};
        class p25 : BaseIcon {idc = NAMETAG_IDC_BASE + 24;};
        class p26 : BaseIcon {idc = NAMETAG_IDC_BASE + 25;};
        class p27 : BaseIcon {idc = NAMETAG_IDC_BASE + 26;};
        class p28 : BaseIcon {idc = NAMETAG_IDC_BASE + 27;};
        class p29 : BaseIcon {idc = NAMETAG_IDC_BASE + 28;};
        class p30 : BaseIcon {idc = NAMETAG_IDC_BASE + 29;};
        class p31 : BaseIcon {idc = NAMETAG_IDC_BASE + 30;};
        class p32 : BaseIcon {idc = NAMETAG_IDC_BASE + 31;};
        class p33 : BaseIcon {idc = NAMETAG_IDC_BASE + 32;};
        class p34 : BaseIcon {idc = NAMETAG_IDC_BASE + 33;};
        class p35 : BaseIcon {idc = NAMETAG_IDC_BASE + 34;};
        class p36 : BaseIcon {idc = NAMETAG_IDC_BASE + 35;};
        class p37 : BaseIcon {idc = NAMETAG_IDC_BASE + 36;};
        class p38 : BaseIcon {idc = NAMETAG_IDC_BASE + 37;};
        class p39 : BaseIcon {idc = NAMETAG_IDC_BASE + 38;};
        class p40 : BaseIcon {idc = NAMETAG_IDC_BASE + 39;};
        class p41 : BaseIcon {idc = NAMETAG_IDC_BASE + 40;};
        class p42 : BaseIcon {idc = NAMETAG_IDC_BASE + 41;};
        class p43 : BaseIcon {idc = NAMETAG_IDC_BASE + 42;};
        class p44 : BaseIcon {idc = NAMETAG_IDC_BASE + 43;};
        class p45 : BaseIcon {idc = NAMETAG_IDC_BASE + 44;};
        class p46 : BaseIcon {idc = NAMETAG_IDC_BASE + 45;};
        class p47 : BaseIcon {idc = NAMETAG_IDC_BASE + 46;};
        class p48 : BaseIcon {idc = NAMETAG_IDC_BASE + 47;};
        class p49 : BaseIcon {idc = NAMETAG_IDC_BASE + 48;};
        class p50 : BaseIcon {idc = NAMETAG_IDC_BASE + 49;};
        class p51 : BaseIcon {idc = NAMETAG_IDC_BASE + 50;};
        class p52 : BaseIcon {idc = NAMETAG_IDC_BASE + 51;};
        class p53 : BaseIcon {idc = NAMETAG_IDC_BASE + 52;};
        class p54 : BaseIcon {idc = NAMETAG_IDC_BASE + 53;};
        class p55 : BaseIcon {idc = NAMETAG_IDC_BASE + 54;};
        class p56 : BaseIcon {idc = NAMETAG_IDC_BASE + 55;};
        class p57 : BaseIcon {idc = NAMETAG_IDC_BASE + 56;};
        class p58 : BaseIcon {idc = NAMETAG_IDC_BASE + 57;};
        class p59 : BaseIcon {idc = NAMETAG_IDC_BASE + 58;};
        class p60 : BaseIcon {idc = NAMETAG_IDC_BASE + 59;};
        class p61 : BaseIcon {idc = NAMETAG_IDC_BASE + 60;};
        class p62 : BaseIcon {idc = NAMETAG_IDC_BASE + 61;};
        class p63 : BaseIcon {idc = NAMETAG_IDC_BASE + 62;};
        class p64 : BaseIcon {idc = NAMETAG_IDC_BASE + 63;};
        class p65 : BaseIcon {idc = NAMETAG_IDC_BASE + 64;};
        class p66 : BaseIcon {idc = NAMETAG_IDC_BASE + 65;};
        class p67 : BaseIcon {idc = NAMETAG_IDC_BASE + 66;};
        class p68 : BaseIcon {idc = NAMETAG_IDC_BASE + 67;};
        class p69 : BaseIcon {idc = NAMETAG_IDC_BASE + 68;};
        class p70 : BaseIcon {idc = NAMETAG_IDC_BASE + 69;};
        class p71 : BaseIcon {idc = NAMETAG_IDC_BASE + 70;};
        class p72 : BaseIcon {idc = NAMETAG_IDC_BASE + 71;};
        class p73 : BaseIcon {idc = NAMETAG_IDC_BASE + 72;};
        class p74 : BaseIcon {idc = NAMETAG_IDC_BASE + 73;};
        class p75 : BaseIcon {idc = NAMETAG_IDC_BASE + 74;};
        class p76 : BaseIcon {idc = NAMETAG_IDC_BASE + 75;};
        class p77 : BaseIcon {idc = NAMETAG_IDC_BASE + 76;};
        class p78 : BaseIcon {idc = NAMETAG_IDC_BASE + 77;};
        class p79 : BaseIcon {idc = NAMETAG_IDC_BASE + 78;};
        class p80 : BaseIcon {idc = NAMETAG_IDC_BASE + 79;};
        class p81 : BaseIcon {idc = NAMETAG_IDC_BASE + 80;};
        class p82 : BaseIcon {idc = NAMETAG_IDC_BASE + 81;};
        class p83 : BaseIcon {idc = NAMETAG_IDC_BASE + 82;};
        class p84 : BaseIcon {idc = NAMETAG_IDC_BASE + 83;};
        class p85 : BaseIcon {idc = NAMETAG_IDC_BASE + 84;};
        class p86 : BaseIcon {idc = NAMETAG_IDC_BASE + 85;};
        class p87 : BaseIcon {idc = NAMETAG_IDC_BASE + 86;};
        class p88 : BaseIcon {idc = NAMETAG_IDC_BASE + 87;};
        class p89 : BaseIcon {idc = NAMETAG_IDC_BASE + 88;};
        class p90 : BaseIcon {idc = NAMETAG_IDC_BASE + 89;};
        class p91 : BaseIcon {idc = NAMETAG_IDC_BASE + 90;};
        class p92 : BaseIcon {idc = NAMETAG_IDC_BASE + 91;};
        class p93 : BaseIcon {idc = NAMETAG_IDC_BASE + 92;};
        class p94 : BaseIcon {idc = NAMETAG_IDC_BASE + 93;};
        class p95 : BaseIcon {idc = NAMETAG_IDC_BASE + 94;};
        class p96 : BaseIcon {idc = NAMETAG_IDC_BASE + 95;};
        class p97 : BaseIcon {idc = NAMETAG_IDC_BASE + 96;};
        class p98 : BaseIcon {idc = NAMETAG_IDC_BASE + 97;};
        class p99 : BaseIcon {idc = NAMETAG_IDC_BASE + 98;};
        class p100 : BaseIcon {idc = NAMETAG_IDC_BASE + 99;};
        class p101 : BaseIcon {idc = NAMETAG_IDC_BASE + 100;};
        class p102 : BaseIcon {idc = NAMETAG_IDC_BASE + 101;};
        class p103 : BaseIcon {idc = NAMETAG_IDC_BASE + 102;};
        class p104 : BaseIcon {idc = NAMETAG_IDC_BASE + 103;};
        class p105 : BaseIcon {idc = NAMETAG_IDC_BASE + 104;};
        class p106 : BaseIcon {idc = NAMETAG_IDC_BASE + 105;};
        class p107 : BaseIcon {idc = NAMETAG_IDC_BASE + 106;};
        class p108 : BaseIcon {idc = NAMETAG_IDC_BASE + 107;};
        class p109 : BaseIcon {idc = NAMETAG_IDC_BASE + 108;};
        class p110 : BaseIcon {idc = NAMETAG_IDC_BASE + 109;};
        class p111 : BaseIcon {idc = NAMETAG_IDC_BASE + 110;};
        class p112 : BaseIcon {idc = NAMETAG_IDC_BASE + 111;};
        class p113 : BaseIcon {idc = NAMETAG_IDC_BASE + 112;};
        class p114 : BaseIcon {idc = NAMETAG_IDC_BASE + 113;};
        class p115 : BaseIcon {idc = NAMETAG_IDC_BASE + 114;};
        class p116 : BaseIcon {idc = NAMETAG_IDC_BASE + 115;};
        class p117 : BaseIcon {idc = NAMETAG_IDC_BASE + 116;};
        class p118 : BaseIcon {idc = NAMETAG_IDC_BASE + 117;};
        class p119 : BaseIcon {idc = NAMETAG_IDC_BASE + 118;};
        class p120 : BaseIcon {idc = NAMETAG_IDC_BASE + 119;};
        class p121 : BaseIcon {idc = NAMETAG_IDC_BASE + 120;};
        class p122 : BaseIcon {idc = NAMETAG_IDC_BASE + 121;};
        class p123 : BaseIcon {idc = NAMETAG_IDC_BASE + 122;};
        class p124 : BaseIcon {idc = NAMETAG_IDC_BASE + 123;};
        class p125 : BaseIcon {idc = NAMETAG_IDC_BASE + 124;};
        class p126 : BaseIcon {idc = NAMETAG_IDC_BASE + 125;};
        class p127 : BaseIcon {idc = NAMETAG_IDC_BASE + 126;};
        class p128 : BaseIcon {idc = NAMETAG_IDC_BASE + 127;};
        class p129 : BaseIcon {idc = NAMETAG_IDC_BASE + 128;};
        class p130 : BaseIcon {idc = NAMETAG_IDC_BASE + 129;};
    };
};